### ISSUE TITLE
How to execute the library

### ISSUE THREAD

**Issue by samyuktha123sets** [boschresearch/pq-wolfSSL#1]
Hi team,

Is there steps for building, executing and generating the certificates using your library.

**Comment by dgarske** [comment]
Hi @samyuktha123sets ,

Yes we have amazing documentation and examples. @anhu will make sure and add any I missed below. 

* https://github.com/wolfSSL/wolfssl-examples/tree/master/pq
* https://github.com/wolfSSL/osp/tree/master/oqs
* https://www.wolfssl.com/documentation/manuals/wolfssl/appendix07.html

Thanks,
David Garske, wolfSSL

**Comment by anhu** [comment]
We also have some great videos on YouTube.

Please see our tutorial for how to setup a post-quantum web server and client: https://www.youtube.com/watch?v=0gveI0_9HYo

If you want to learn about post-quantum cryptography in general, you can watch our guest webinar with Professor Douglas Stebila:  https://www.youtube.com/watch?v=nOcRk5jVGYU

**Comment by samyuktha123sets** [comment]
Hi,
Does the implementation generate and verify certificates using Dilithium, FALCON, SPHINCS and XMSS on the embedded device (Raspberry Pi 3 Cortex A53)?

Regards
Samyuktha

**Comment by anhu** [comment]
Please have a look here: https://github.com/wolfSSL/osp/tree/master/oqs

The `README.md` says to use the scripts to generate the certificate chains. Note that it is using OQS's fork of OpenSSL to do this.  It could probably work on Raspberry Pi 3, but we tested on `x86_64`. 

Warm regards, Anthony
