### ISSUE TITLE
Error in generating certificates

### ISSUE THREAD

**Issue by meghaii** [boschresearch/pq-wolfSSL#3]
Hello Team,
I am getting a following error while generating certificates on my system:
**/certgen: symbol lookup error: ./certgen: undefined symbol: wc_FalconKeyToDer**

Could you please help in resolving?

Thanks

**Comment by pykqdtc** [comment]
Hi @meghaii 

make sure to enable the Falcon signature scheme when setting up the build environment via the ./configure script by adding --enable-falcon. 

But if you'd like to evaluate PQC support I recommend to look at the official wolfSSL repository, which includes support for NIST PQC schemes: [https://github.com/wolfSSL/wolfssl](https://github.com/wolfSSL/wolfssl).

This fork was done by a team at Bosch Research only for a [scientific publication](https://eprint.iacr.org/2021/1447) and is no longer actively maintained.
