### ISSUE TITLE
Possible variable-time division when decapsulating in Kyber

### ISSUE THREAD

**Issue by xvzcf** [boschresearch/pq-wolfSSL#4]
This bit of code is used in compressing a polynomial ring element into a (secret) message:

https://github.com/boschresearch/pq-wolfSSL/blob/f10c3b08856e5d0737b19e647f7a49c0eb753836/wolfcrypt/src/kyber_polynoms.c#L447

To do so, it performs a division by Q that might not necessarily compile to a multiplication instruction: looking at the output of some C compilers using https://godbolt.org/z/sKn3TKKGq and https://godbolt.org/z/8GqKoTfYh for example, a division instruction is emitted even when -O3 is specified. Should a division instruction be emitted, its execution time would likely be variable and leak information about its secret input.

We reported a similar issue in the CRYSTALS-Kyber reference implementation; you may want to use their fix: https://github.com/pq-crystals/kyber/commit/dda29cc63af721981ee2c831cf00822e69be3220

**Comment by pykqdtc** [comment]
Thanks for pointing this out @xvzcf! I applied the proposed fixes for KyberSlash1 (pq-crystals/kyber@dda29cc) and KyberSlash2 (pq-crystals/kyber@272125f).
